### ISSUE TITLE
PermissionDenied on Ubuntu 

### ISSUE THREAD

**Issue by adrianbrink** [ZondaX/ledger-rs#3]
Running the tests on `Ubuntu 18.01` with a connected and unlocked ledger results in. `serialize` always works, but `list_all_devices` only sometimes works.
```
➜  ledger-rs git:(master) cargo test -- --nocapture
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running target/debug/deps/ledger-3e8d643c858b814b

running 4 tests
test integration_tests::serialize ... ok
thread 'integration_tests::exchange' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
test integration_tests::exchange ... FAILED
thread 'integration_tests::ledger_device_path' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', src/libcore/result.rs:997:5
thread 'integration_tests::list_all_devices' panicked at 'Could not lock api wrapper: "PoisonError { inner: .. }"', src/libcore/result.rs:test integration_tests::ledger_device_path ... FAILED
997:5
test integration_tests::list_all_devices ... FAILED

failures:

failures:
    integration_tests::exchange
    integration_tests::ledger_device_path
    integration_tests::list_all_devices

test result: FAILED. 1 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
➜  ledger-rs git:(master) cargo test -- --nocapture
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running target/debug/deps/ledger-3e8d643c858b814b

running 4 tests
test integration_tests::serialize ... ok
"/dev/hidraw2" - 0x46d/0x20 Logitech USB Receiver
"/dev/hidraw3" - 0x46d/0x2d31 Logitech USB Receiver
"/dev/hidraw4" - 0x46d/0x2d31 Logitech USB Receiver
"/dev/hidraw1" - 0x46d/0x2d31 Logitech USB Receiver
"/dev/hidraw0" - 0x2c97/0x2e32 Ledger Nano S
"/dev/hidraw5" - 0x2c97/0x2f30 Ledger Nano S
test integration_tests::list_all_devices ... ok
thread 'integration_tests::ledger_device_path' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'integration_tests::exchange' panicked at 'Could not lock api wrapper: "PoisonError { inner: .. }"', src/libcore/result.rstest integration_tests::ledger_device_path ... :997FAILED:
5
test integration_tests::exchange ... FAILED

failures:

failures:
    integration_tests::exchange
    integration_tests::ledger_device_path

test result: FAILED. 2 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
```

On `macOS` the tests pass.

**Comment by jleni** [comment]
This is strange. I cannot reproduce any permission problems..
Are you running any special configuration? a VM for instance?

**Comment by jleni** [comment]
permission problems sound more like a OS related issue

**Comment by adrianbrink** [comment]
The issue appeared on my desktop machine that runs bare metal Ubuntu. 

I just realised that I had this issue before with the Tezos baking application. There I needed to setup udev rules with this [script](https://github.com/obsidiansystems/ledger-app-tezos/blob/master/README.md#udev-rules-linux-only).

I'll try that later today.

**Comment by jleni** [comment]
@adrianbrink do you still have this issue? Can we close this it otherwise?

**Comment by adrianbrink** [comment]
No, the udev thing fixed it.
